"""Translations of the AirReveal 2.0 home page (index.html, the English source) for the five other languages,
keyed by the English text exactly as it appears on the page. Used by site_v2_home.py.

Feature names follow the app's own translations (Localizable.xcstrings), and the tone follows the rest of the
site: du (de), tú (es), vous (fr), tu (it), você (pt-BR). Distances are in kilometres outside English."""

STRINGS = {
"de": {
 "Discover what's above and below.": "Entdecke, was darüber und darunter ist.", "Discover what's above and below": "Entdecke, was darüber und darunter ist",
 "AirReveal: What Am I Flying Over? Flight Map & Sky Radar": "AirReveal: Was überfliege ich? Flugkarte & Himmelsradar",
 "See what you're flying over on your own flight, even in airplane mode, and every plane flying over you on the ground. An offline flight map and live sky radar for iPhone, iPad and Apple Watch.":
   "Sieh auf deinem eigenen Flug, was du überfliegst, auch im Flugmodus, und am Boden jedes Flugzeug, das über dich fliegt. Offline-Flugkarte und Live-Himmelsradar für iPhone, iPad und Apple Watch.",
 "Below you": "Unter dir", "Above you": "Über dir", "Games": "Spiele", "Pricing": "Preise", "FAQ": "FAQ", "Get the app": "App laden",
 "Flight map & sky radar · iPhone, iPad & Apple Watch": "Flugkarte & Himmelsradar · iPhone, iPad & Apple Watch",
 "Discover what's above or below you.": "Entdecke, was über oder unter dir ist.",
 "From your window seat, AirReveal names the mountains, cities and coastlines below, even in airplane mode. On the ground, it shows every plane flying over you, where it's going, and the police and air ambulance helicopters in their own colours.":
   "Am Fensterplatz benennt AirReveal die Berge, Städte und Küsten unter dir, auch im Flugmodus. Am Boden zeigt es jedes Flugzeug über dir, wohin es fliegt, und Polizei- und Rettungshubschrauber in ihren eigenen Farben.",
 "Download on the": "Laden im", "Free to start · 2.0 is here": "Kostenlos starten · 2.0 ist da",
 "Departures": "Abflüge", "New in 2.0": "Neu in 2.0", "Flight": "Flug", "Feature": "Funktion", "Gate": "Gate", "Status": "Status",
 "Above you · every aircraft overhead": "Über dir · jedes Flugzeug am Himmel", "Boarding": "Boarding",
 "Follow any plane on the map": "Jedem Flugzeug auf der Karte folgen", "On time": "Planmäßig",
 "Emergency aircraft in their colours": "Einsatzflugzeuge in ihren Farben", "New": "Neu",
 "Apple Watch & watch faces": "Apple Watch & Zifferblätter", "Live Activity & widgets": "Live-Aktivität & Widgets",
 "Spotter's Logbook & Sky Bingo": "Spotter-Logbuch & Himmelsbingo", "Split-flap & Information Board looks": "Fallblatt- & Anzeigetafel-Stil",
 "Follow Me · your flight": "Folge mir · dein Flug", "The world beneath your wings.": "Die Welt unter deinen Flügeln.",
 "Track your flight by GPS, even in airplane mode, and AirReveal names the mountains, cities and coastlines below as you pass them.":
   "Verfolge deinen Flug per GPS, auch im Flugmodus, und AirReveal benennt die Berge, Städte und Küsten unter dir, während du sie überfliegst.",
 "Live": "Live", "Your position on a full-screen map, with no Wi-Fi needed on board.": "Deine Position auf einer Vollbildkarte, ohne WLAN an Bord.",
 "Plan": "Plan", "Fly the whole route before you go and see what's coming.": "Flieg die ganze Route vorab und sieh, was dich erwartet.",
 "Window View": "Fensterblick", "Hold your phone to the window and landmarks are labelled on the camera picture.": "Halte dein iPhone ans Fenster, und Sehenswürdigkeiten werden im Kamerabild beschriftet.",
 "Best side to sit": "Die beste Seite", "Left or right, which landmarks you'll see, and whether you'll catch the sunset.": "Links oder rechts: welche Sehenswürdigkeiten du siehst und ob du den Sonnenuntergang erwischst.",
 "Flight HUD": "Flug-HUD", "Altitude, speed and heading over the map, and on the Lock Screen.": "Höhe, Geschwindigkeit und Kurs über der Karte und auf dem Sperrbildschirm.",
 "Journal": "Journal", "Every trip kept, replayed from where you left off.": "Jede Reise gespeichert, abgespielt ab dort, wo du aufgehört hast.",
 "Window-seat companion": "Begleiter für den Fensterplatz", "What am I flying over?": "Was überfliege ich gerade?",
 "Every window seat raises the same question. AirReveal answers it at 38,000 feet with only your phone's GPS: download your flight's maps and landmarks before you board, and you're set.":
   "An jedem Fensterplatz stellt sich dieselbe Frage. AirReveal beantwortet sie in 38.000 Fuß nur mit dem GPS deines iPhone: Lade Karten und Sehenswürdigkeiten deines Flugs vor dem Einsteigen, und du bist bereit.",
 "Works in airplane mode": "Funktioniert im Flugmodus", "Offline maps": "Offline-Karten", "Landmarks named as you pass": "Sehenswürdigkeiten beim Überfliegen benannt", "Golden-hour side": "Seite für die goldene Stunde",
 "Follow You · the sky around you": "Ich folge dir · der Himmel um dich", "Who's flying over?": "Wer fliegt da drüber?",
 "Every aircraft around you on a radar and a live map, from free community flight data. Tap one to reveal it.": "Jedes Flugzeug um dich herum auf einem Radar und einer Live-Karte, aus freien Community-Flugdaten. Tippe eines an, um es zu enthüllen.",
 "Above You Now": "Gerade über dir", "The nearest aircraft, how far and which way, with the radar turning to where you face.": "Das nächste Flugzeug, wie weit und in welcher Richtung, mit einem Radar, das sich nach deiner Blickrichtung dreht.",
 "Day and night maps": "Karten für Tag und Nacht", "Choose the map type; after sunset, Night Lights shows the streets lit below.": "Wähle den Kartentyp; nach Sonnenuntergang zeigt Nachtlichter die beleuchteten Straßen darunter.",
 "Look up with the camera": "Mit der Kamera nach oben schauen", "Point at the sky and each plane is marked where it is.": "Richte die Kamera auf den Himmel, und jedes Flugzeug wird dort markiert, wo es ist.",
 "Aircraft cards": "Flugzeugkarten", "A photo of that very aircraft, its route, height, speed and type.": "Ein Foto genau dieses Flugzeugs, seine Route, Höhe, Geschwindigkeit und sein Typ.",
 "Follow it": "Folge ihm", "Keep a plane on the map up to 500 miles away, along the track it really flew.": "Behalte ein Flugzeug bis zu 800 km entfernt auf der Karte, entlang der Strecke, die es wirklich geflogen ist.",
 "Helicopters too": "Auch Hubschrauber", "Shown with their own icon, so you know what you're hearing.": "Mit eigenem Symbol, damit du weißt, was du hörst.",
 "Blue lights, spotted.": "Blaulicht am Himmel.",
 "Police, air ambulance, coastguard, firefighting and military aircraft stand out in their own service's colours. Turn on alerts and AirReveal tells you when one comes near, even with the app closed.":
   "Polizei, Luftrettung, Küstenwache, Brandbekämpfung und Militär heben sich in den Farben ihres Dienstes ab. Schalte Hinweise ein, und AirReveal sagt dir Bescheid, wenn eines in die Nähe kommt, auch bei geschlossener App.",
 "Air ambulance nearby": "Luftrettung in der Nähe", "HLE80 (A169), 2 mi NE of you": "HLE80 (A169), 3 km NO von dir",
 "Police": "Polizei", "Black and yellow, as in the UK": "Schwarz und Gelb, wie in Großbritannien", "Air ambulance": "Luftrettung", "Yellow and green": "Gelb und Grün",
 "Coastguard": "Küstenwache", "HM Coastguard red and white": "Rot und Weiß der britischen Küstenwache", "Firefighting": "Brandbekämpfung", "Yellow and red": "Gelb und Rot",
 "Military": "Militär", "Olive drab": "Olivgrün", "BAW507 · 3 mi E": "BAW507 · 5 km O",
 "Beyond the app": "Über die App hinaus", "On your wrist, Lock Screen and Home Screen.": "Am Handgelenk, auf dem Sperr- und Home-Bildschirm.",
 "A radar you zoom with the Digital Crown, an arrow that points to the plane as you turn, and your flight's progress.": "Ein Radar, das du mit der Digital Crown zoomst, ein Pfeil, der beim Drehen auf das Flugzeug zeigt, und der Fortschritt deines Flugs.",
 "Watch faces and Smart Stack": "Zifferblätter und Smart-Stapel", "The nearest aircraft, or the one you follow, right on your watch face.": "Das nächste Flugzeug, oder das, dem du folgst, direkt auf deinem Zifferblatt.",
 "Live Activities": "Live-Aktivitäten", "The plane you follow on the Lock Screen and in the Dynamic Island: how far, which way, how high.": "Das Flugzeug, dem du folgst, auf dem Sperrbildschirm und in der Dynamic Island: wie weit, in welcher Richtung, wie hoch.",
 "Widgets": "Widgets", "Above You on the Home Screen and the Lock Screen, with the radar.": "Über dir auf dem Home- und Sperrbildschirm, mit dem Radar.",
 "Play along, or don't": "Spiel mit – oder nicht", "Every plane counts.": "Jedes Flugzeug zählt.",
 "Games for both halves, on your own flights and with the planes above you. Not your thing? Turn them off in Settings and AirReveal is a clean flight tracker.":
   "Spiele für beide Seiten, auf deinen eigenen Flügen und mit den Flugzeugen über dir. Nichts für dich? Schalte sie in den Einstellungen aus, und AirReveal ist ein schlichter Flugtracker.",
 "Spotter's Logbook": "Spotter-Logbuch", "Every aircraft you reveal, rated common, rare or legendary, with your personal bests.": "Jedes Flugzeug, das du enthüllst, als häufig, selten oder legendär eingestuft, mit deinen Bestwerten.",
 "Bingo and challenges": "Bingo und Herausforderungen", "Discovery Bingo on your flight, Sky Bingo from home, and three small challenges a day.": "Entdeckungs-Bingo auf deinem Flug, Himmelsbingo von zu Hause und drei kleine Herausforderungen am Tag.",
 "Achievements": "Erfolge", "Stamp your passport, collect landmarks, and spot every emergency service for a badge.": "Stempel deinen Reisepass, sammle Sehenswürdigkeiten und entdecke jeden Einsatzdienst für ein Abzeichen.",
 "Make it yours": "Ganz nach deinem Geschmack", "Three looks, one app.": "Drei Stile, eine App.",
 "ABOVE YOU": "ÜBER DIR", "BAW507 12,000 FT": "BAW507 12.000 FT", "3 MI NE · CLOSE": "5 KM NO · NAH",
 "Split-Flap": "Fallblatt", "The flip-letter departure boards: amber on black.": "Die klappernden Abflugtafeln: Bernstein auf Schwarz.",
 "✈ BAW507": "✈ BAW507", "12,000 ft": "12.000 ft", "Distance": "Entfernung", "3 mi NE": "5 km NO", "Close": "Nah",
 "Information Board": "Anzeigetafel", "A modern airport screen: white and gold on deep navy.": "Ein moderner Flughafenbildschirm: Weiß und Gold auf tiefem Marineblau.",
 "BAW507 · A21N": "BAW507 · A21N", "3 mi NE · 12,000 ft": "5 km NO · 12.000 ft",
 "AirReveal Classic": "AirReveal Klassisch", "Cards in your colour theme, in Light or Dark.": "Karten in deinem Farbthema, hell oder dunkel.",
 "Made for every window seat": "Für jeden Fensterplatz gemacht", "Whoever you are, however often you fly.": "Wer du auch bist, wie oft du auch fliegst.",
 "Aviation fans": "Luftfahrtfans", "Altitude, speed and heading, aircraft types, and a logbook of every plane you spot.": "Höhe, Geschwindigkeit und Kurs, Flugzeugtypen und ein Logbuch jedes Flugzeugs, das du entdeckst.",
 "Business travellers": "Geschäftsreisende", "A calm map for the same route every week, with something new to notice each time.": "Eine ruhige Karte für dieselbe Route jede Woche, mit jedes Mal etwas Neuem zu entdecken.",
 "Families and holidays": "Familien und Urlaub", "Which side to sit, what's below, and bingo to keep everyone looking out of the window.": "Welche Seite die beste ist, was unten liegt, und Bingo, damit alle aus dem Fenster schauen.",
 "Curious minds": "Neugierige Köpfe", "Trivia about every landmark and aircraft type, from home or 38,000 feet.": "Wissenswertes über jede Sehenswürdigkeit und jeden Flugzeugtyp, von zu Hause oder aus 38.000 Fuß.",
 "Take the tour": "Rundgang", "AirReveal 2.0, screen by screen": "AirReveal 2.0, Bildschirm für Bildschirm",
 "Choose your way to fly": "Wähle, wie du fliegst", "Plan freely. Go Pro when you want more.": "Plane kostenlos. Hol dir Pro, wenn du mehr willst.",
 "Questions": "Fragen", "Flying over, answered.": "Was du überfliegst, beantwortet.",
 "Final call": "Letzter Aufruf", "Adventure flies with you.": "Das Abenteuer fliegt mit.",
 "AirReveal is on the App Store for iPhone, iPad and Apple Watch. Free to start.": "AirReveal gibt es im App Store für iPhone, iPad und Apple Watch. Kostenlos starten.",
 "User guide": "Benutzerhandbuch", "Support": "Support", "Privacy": "Datenschutz", "Terms": "Nutzungsbedingungen", "Data and credits": "Daten und Quellen", "Feedback board": "Feedback-Board",
 "© 2026 iSafeNet. Aircraft data from ADSB.lol (ODbL) and plane-alert-db (ODbL). Not an official flight-status or air-traffic service.": "© 2026 iSafeNet. Flugzeugdaten von ADSB.lol (ODbL) und plane-alert-db (ODbL). Kein offizieller Flugstatus- oder Flugsicherungsdienst.",
 "Photos on Unsplash: Zac Ong, Kotryna Juskaite, Ben Klewais, Patrick Fore, Nicolas Houdayer.": "Fotos auf Unsplash: Zac Ong, Kotryna Juskaite, Ben Klewais, Patrick Fore, Nicolas Houdayer.",
 "Main": "Hauptmenü", "AirReveal's home screen: live tracking of your flight and the aircraft above you now": "Der Startbildschirm von AirReveal: Live-Verfolgung deines Flugs und die Flugzeuge gerade über dir",
 "What's new in AirReveal 2.0": "Neu in AirReveal 2.0", "Live flight map": "Live-Flugkarte", "Explore what's below": "Entdecke, was unter dir liegt",
 "Above You map around London": "Über-dir-Karte rund um London", "Sky camera naming planes overhead": "Himmelskamera, die Flugzeuge über dir benennt", "Example notification": "Beispielmitteilung",
 "Following a plane with its recorded track": "Einem Flugzeug mit seiner aufgezeichneten Strecke folgen", "Flight journal": "Flugjournal", "Landmarks to discover": "Sehenswürdigkeiten zum Entdecken",
 "Screenshots, scroll sideways": "Bildschirmfotos, seitlich scrollen", "Discover what's above or below you": "Entdecke, was über oder unter dir ist", "See where you are": "Sieh, wo du bist",
 "Discover what's below": "Entdecke, was unter dir liegt", "Planes above you": "Flugzeuge über dir", "Point at the sky": "Zeig auf den Himmel", "Follow any plane": "Folge jedem Flugzeug",
 "Journal and logbook": "Journal und Logbuch", "Play as you go": "Spiel unterwegs", "Make it yours": "Ganz nach deinem Geschmack",
 "Spotter's Logbook": "Spotter-Logbuch", "Following a plane": "Einem Flugzeug folgen",
 "Also in": "Auch auf",
},
"es": {
 "Discover what's above and below.": "Descubre lo que hay arriba y abajo.", "Discover what's above and below": "Descubre lo que hay arriba y abajo",
 "Choose your way to fly": "Elige cómo volar", "Following a plane": "Siguiendo un avión", "Plan freely. Go Pro when you want more.": "Planifica gratis. Pásate a Pro cuando quieras más.",
 "AirReveal: What Am I Flying Over? Flight Map & Sky Radar": "AirReveal: ¿Qué estoy sobrevolando? Mapa de vuelo y radar del cielo",
 "See what you're flying over on your own flight, even in airplane mode, and every plane flying over you on the ground. An offline flight map and live sky radar for iPhone, iPad and Apple Watch.":
   "Mira lo que sobrevuelas en tu propio vuelo, incluso en modo avión, y en tierra cada avión que pasa por encima de ti. Un mapa de vuelo sin conexión y un radar del cielo en directo para iPhone, iPad y Apple Watch.",
 "Below you": "Debajo de ti", "Above you": "Encima de ti", "Games": "Juegos", "Pricing": "Precios", "FAQ": "Preguntas", "Get the app": "Descargar",
 "Flight map & sky radar · iPhone, iPad & Apple Watch": "Mapa de vuelo y radar del cielo · iPhone, iPad y Apple Watch",
 "Discover what's above or below you.": "Descubre lo que hay encima o debajo de ti.",
 "From your window seat, AirReveal names the mountains, cities and coastlines below, even in airplane mode. On the ground, it shows every plane flying over you, where it's going, and the police and air ambulance helicopters in their own colours.":
   "Desde la ventanilla, AirReveal nombra las montañas, ciudades y costas que hay debajo, incluso en modo avión. En tierra, muestra cada avión que vuela sobre ti, adónde va, y los helicópteros de policía y ambulancia aérea con sus propios colores.",
 "Download on the": "Descárgalo en el", "Free to start · 2.0 is here": "Gratis para empezar · Ya está aquí la 2.0",
 "Departures": "Salidas", "New in 2.0": "Novedades de la 2.0", "Flight": "Vuelo", "Feature": "Función", "Gate": "Puerta", "Status": "Estado",
 "Above you · every aircraft overhead": "Encima de ti · cada avión en el cielo", "Boarding": "Embarcando",
 "Follow any plane on the map": "Sigue cualquier avión en el mapa", "On time": "A tiempo",
 "Emergency aircraft in their colours": "Aeronaves de emergencia con sus colores", "New": "Nuevo",
 "Apple Watch & watch faces": "Apple Watch y esferas", "Live Activity & widgets": "Actividad en directo y widgets",
 "Spotter's Logbook & Sky Bingo": "Cuaderno de avistamientos y Bingo del cielo", "Split-flap & Information Board looks": "Estilos Paletas y Panel informativo",
 "Follow Me · your flight": "Sígueme · tu vuelo", "The world beneath your wings.": "El mundo bajo tus alas.",
 "Track your flight by GPS, even in airplane mode, and AirReveal names the mountains, cities and coastlines below as you pass them.":
   "Sigue tu vuelo por GPS, incluso en modo avión, y AirReveal nombra las montañas, ciudades y costas que hay debajo a medida que pasas.",
 "Live": "En directo", "Your position on a full-screen map, with no Wi-Fi needed on board.": "Tu posición en un mapa a pantalla completa, sin necesidad de wifi a bordo.",
 "Plan": "Plan", "Fly the whole route before you go and see what's coming.": "Recorre toda la ruta antes de salir y mira lo que te espera.",
 "Window View": "Vista desde la ventanilla", "Hold your phone to the window and landmarks are labelled on the camera picture.": "Acerca el iPhone a la ventanilla y los lugares de interés aparecen señalados en la imagen de la cámara.",
 "Best side to sit": "El mejor lado", "Left or right, which landmarks you'll see, and whether you'll catch the sunset.": "Izquierda o derecha, qué lugares verás y si te tocará la puesta de sol.",
 "Flight HUD": "HUD de vuelo", "Altitude, speed and heading over the map, and on the Lock Screen.": "Altitud, velocidad y rumbo sobre el mapa y en la pantalla de bloqueo.",
 "Journal": "Diario", "Every trip kept, replayed from where you left off.": "Cada viaje guardado, para reproducirlo desde donde lo dejaste.",
 "Window-seat companion": "Tu compañero de ventanilla", "What am I flying over?": "¿Qué estoy sobrevolando?",
 "Every window seat raises the same question. AirReveal answers it at 38,000 feet with only your phone's GPS: download your flight's maps and landmarks before you board, and you're set.":
   "Cada ventanilla plantea la misma pregunta. AirReveal la responde a 38.000 pies solo con el GPS de tu iPhone: descarga los mapas y lugares de tu vuelo antes de embarcar y listo.",
 "Works in airplane mode": "Funciona en modo avión", "Offline maps": "Mapas sin conexión", "Landmarks named as you pass": "Lugares nombrados al pasar", "Golden-hour side": "El lado de la hora dorada",
 "Follow You · the sky around you": "Te sigo · el cielo a tu alrededor", "Who's flying over?": "¿Quién vuela por encima?",
 "Every aircraft around you on a radar and a live map, from free community flight data. Tap one to reveal it.": "Cada avión a tu alrededor en un radar y un mapa en directo, con datos de vuelo libres de la comunidad. Toca uno para descubrirlo.",
 "Above You Now": "Encima de ti ahora", "The nearest aircraft, how far and which way, with the radar turning to where you face.": "El avión más cercano, a qué distancia y en qué dirección, con el radar girando hacia donde miras.",
 "Day and night maps": "Mapas de día y de noche", "Choose the map type; after sunset, Night Lights shows the streets lit below.": "Elige el tipo de mapa; tras la puesta de sol, Luces nocturnas muestra las calles iluminadas.",
 "Look up with the camera": "Mira hacia arriba con la cámara", "Point at the sky and each plane is marked where it is.": "Apunta al cielo y cada avión aparece marcado donde está.",
 "Aircraft cards": "Fichas de aviones", "A photo of that very aircraft, its route, height, speed and type.": "Una foto de ese mismo avión, su ruta, altura, velocidad y tipo.",
 "Follow it": "Síguelo", "Keep a plane on the map up to 500 miles away, along the track it really flew.": "Mantén un avión en el mapa hasta a 800 km, por la ruta que de verdad voló.",
 "Helicopters too": "También helicópteros", "Shown with their own icon, so you know what you're hearing.": "Con su propio icono, para que sepas qué estás oyendo.",
 "Blue lights, spotted.": "Luces azules, a la vista.",
 "Police, air ambulance, coastguard, firefighting and military aircraft stand out in their own service's colours. Turn on alerts and AirReveal tells you when one comes near, even with the app closed.":
   "Las aeronaves de policía, ambulancia aérea, guardacostas, extinción de incendios y militares destacan con los colores de su servicio. Activa los avisos y AirReveal te dirá cuándo se acerca una, incluso con la app cerrada.",
 "Air ambulance nearby": "Ambulancia aérea cerca", "HLE80 (A169), 2 mi NE of you": "HLE80 (A169), a 3 km al NE de ti",
 "Police": "Policía", "Black and yellow, as in the UK": "Negro y amarillo, como en el Reino Unido", "Air ambulance": "Ambulancia aérea", "Yellow and green": "Amarillo y verde",
 "Coastguard": "Guardacostas", "HM Coastguard red and white": "Rojo y blanco de la Guardia Costera británica", "Firefighting": "Extinción de incendios", "Yellow and red": "Amarillo y rojo",
 "Military": "Militar", "Olive drab": "Verde oliva", "BAW507 · 3 mi E": "BAW507 · 5 km E",
 "Beyond the app": "Más allá de la app", "On your wrist, Lock Screen and Home Screen.": "En tu muñeca, en la pantalla de bloqueo y en la de inicio.",
 "A radar you zoom with the Digital Crown, an arrow that points to the plane as you turn, and your flight's progress.": "Un radar que amplías con la Digital Crown, una flecha que apunta al avión mientras giras y el progreso de tu vuelo.",
 "Watch faces and Smart Stack": "Esferas y Pila inteligente", "The nearest aircraft, or the one you follow, right on your watch face.": "El avión más cercano, o el que sigues, en tu esfera.",
 "Live Activities": "Actividades en directo", "The plane you follow on the Lock Screen and in the Dynamic Island: how far, which way, how high.": "El avión que sigues en la pantalla de bloqueo y en la Dynamic Island: a qué distancia, en qué dirección, a qué altura.",
 "Widgets": "Widgets", "Above You on the Home Screen and the Lock Screen, with the radar.": "Encima de ti en la pantalla de inicio y en la de bloqueo, con el radar.",
 "Play along, or don't": "Juega, o no", "Every plane counts.": "Cada avión cuenta.",
 "Games for both halves, on your own flights and with the planes above you. Not your thing? Turn them off in Settings and AirReveal is a clean flight tracker.":
   "Juegos para las dos mitades, en tus propios vuelos y con los aviones que pasan por encima. ¿No es lo tuyo? Desactívalos en Ajustes y AirReveal es un rastreador de vuelos sin más.",
 "Spotter's Logbook": "Cuaderno de avistamientos", "Every aircraft you reveal, rated common, rare or legendary, with your personal bests.": "Cada avión que descubres, clasificado como común, raro o legendario, con tus mejores marcas.",
 "Bingo and challenges": "Bingo y retos", "Discovery Bingo on your flight, Sky Bingo from home, and three small challenges a day.": "Bingo de Descubrimientos en tu vuelo, Bingo del cielo desde casa y tres pequeños retos al día.",
 "Achievements": "Logros", "Stamp your passport, collect landmarks, and spot every emergency service for a badge.": "Sella tu pasaporte, colecciona lugares y avista cada servicio de emergencia para ganar una insignia.",
 "Make it yours": "A tu manera", "Three looks, one app.": "Tres estilos, una app.",
 "ABOVE YOU": "ENCIMA DE TI", "BAW507 12,000 FT": "BAW507 12.000 FT", "3 MI NE · CLOSE": "5 KM NE · CERCA",
 "Split-Flap": "Paletas", "The flip-letter departure boards: amber on black.": "Los paneles de salidas de paletas: ámbar sobre negro.",
 "✈ BAW507": "✈ BAW507", "12,000 ft": "12.000 ft", "Distance": "Distancia", "3 mi NE": "5 km NE", "Close": "Cerca",
 "Information Board": "Panel informativo", "A modern airport screen: white and gold on deep navy.": "Una pantalla de aeropuerto moderna: blanco y dorado sobre azul marino.",
 "BAW507 · A21N": "BAW507 · A21N", "3 mi NE · 12,000 ft": "5 km NE · 12.000 ft",
 "AirReveal Classic": "AirReveal clásico", "Cards in your colour theme, in Light or Dark.": "Tarjetas con tu tema de color, en claro u oscuro.",
 "Made for every window seat": "Para cada ventanilla", "Whoever you are, however often you fly.": "Seas quien seas, vueles cuanto vueles.",
 "Aviation fans": "Aficionados a la aviación", "Altitude, speed and heading, aircraft types, and a logbook of every plane you spot.": "Altitud, velocidad y rumbo, tipos de avión y un cuaderno de cada avión que avistas.",
 "Business travellers": "Viajeros de negocios", "A calm map for the same route every week, with something new to notice each time.": "Un mapa tranquilo para la misma ruta cada semana, con algo nuevo que descubrir cada vez.",
 "Families and holidays": "Familias y vacaciones", "Which side to sit, what's below, and bingo to keep everyone looking out of the window.": "En qué lado sentarse, qué hay debajo y un bingo para que todos miren por la ventanilla.",
 "Curious minds": "Mentes curiosas", "Trivia about every landmark and aircraft type, from home or 38,000 feet.": "Curiosidades sobre cada lugar y tipo de avión, desde casa o a 38.000 pies.",
 "Take the tour": "Haz el recorrido", "AirReveal 2.0, screen by screen": "AirReveal 2.0, pantalla a pantalla",
 "Questions": "Preguntas", "Flying over, answered.": "Lo que sobrevuelas, resuelto.",
 "Final call": "Última llamada", "Adventure flies with you.": "La aventura vuela contigo.",
 "AirReveal is on the App Store for iPhone, iPad and Apple Watch. Free to start.": "AirReveal está en la App Store para iPhone, iPad y Apple Watch. Gratis para empezar.",
 "User guide": "Guía de uso", "Support": "Soporte", "Privacy": "Privacidad", "Terms": "Condiciones", "Data and credits": "Datos y créditos", "Feedback board": "Tablón de sugerencias",
 "© 2026 iSafeNet. Aircraft data from ADSB.lol (ODbL) and plane-alert-db (ODbL). Not an official flight-status or air-traffic service.": "© 2026 iSafeNet. Datos de aviones de ADSB.lol (ODbL) y plane-alert-db (ODbL). No es un servicio oficial de estado de vuelos ni de tráfico aéreo.",
 "Photos on Unsplash: Zac Ong, Kotryna Juskaite, Ben Klewais, Patrick Fore, Nicolas Houdayer.": "Fotos en Unsplash: Zac Ong, Kotryna Juskaite, Ben Klewais, Patrick Fore, Nicolas Houdayer.",
 "Main": "Principal", "AirReveal's home screen: live tracking of your flight and the aircraft above you now": "La pantalla de inicio de AirReveal: tu vuelo en directo y los aviones encima de ti ahora",
 "What's new in AirReveal 2.0": "Novedades de AirReveal 2.0", "Live flight map": "Mapa de vuelo en directo", "Explore what's below": "Explora lo que hay debajo",
 "Above You map around London": "Mapa Encima de ti alrededor de Londres", "Sky camera naming planes overhead": "Cámara del cielo nombrando los aviones", "Example notification": "Notificación de ejemplo",
 "Following a plane with its recorded track": "Siguiendo un avión con su ruta registrada", "Flight journal": "Diario de vuelos", "Landmarks to discover": "Lugares por descubrir",
 "Screenshots, scroll sideways": "Capturas, desliza hacia los lados", "Discover what's above or below you": "Descubre lo que hay encima o debajo de ti", "See where you are": "Mira dónde estás",
 "Discover what's below": "Descubre lo que hay debajo", "Planes above you": "Aviones encima de ti", "Point at the sky": "Apunta al cielo", "Follow any plane": "Sigue cualquier avión",
 "Journal and logbook": "Diario y cuaderno", "Play as you go": "Juega mientras viajas", "Also in": "También en",
},
"fr": {
 "Discover what's above and below.": "Découvrez ce qui est au-dessus et en dessous.", "Discover what's above and below": "Découvrez ce qui est au-dessus et en dessous",
 "Choose your way to fly": "Choisissez votre façon de voler", "Following a plane": "Suivre un avion", "Plan freely. Go Pro when you want more.": "Planifiez gratuitement. Passez à Pro quand vous voulez plus.",
 "AirReveal: What Am I Flying Over? Flight Map & Sky Radar": "AirReveal : qu'est-ce que je survole ? Carte de vol et radar du ciel",
 "See what you're flying over on your own flight, even in airplane mode, and every plane flying over you on the ground. An offline flight map and live sky radar for iPhone, iPad and Apple Watch.":
   "Voyez ce que vous survolez pendant votre vol, même en mode avion, et au sol chaque avion qui passe au-dessus de vous. Une carte de vol hors ligne et un radar du ciel en direct pour iPhone, iPad et Apple Watch.",
 "Below you": "En dessous", "Above you": "Au-dessus", "Games": "Jeux", "Pricing": "Tarifs", "FAQ": "FAQ", "Get the app": "Obtenir l'app",
 "Flight map & sky radar · iPhone, iPad & Apple Watch": "Carte de vol et radar du ciel · iPhone, iPad et Apple Watch",
 "Discover what's above or below you.": "Découvrez ce qui est au-dessus ou en dessous de vous.",
 "From your window seat, AirReveal names the mountains, cities and coastlines below, even in airplane mode. On the ground, it shows every plane flying over you, where it's going, and the police and air ambulance helicopters in their own colours.":
   "Depuis votre hublot, AirReveal nomme les montagnes, villes et côtes en dessous, même en mode avion. Au sol, il montre chaque avion qui passe au-dessus de vous, sa destination, et les hélicoptères de police et d'ambulance aérienne à leurs propres couleurs.",
 "Download on the": "Télécharger dans l'", "Free to start · 2.0 is here": "Gratuit pour commencer · La 2.0 est là",
 "Departures": "Départs", "New in 2.0": "Nouveautés de la 2.0", "Flight": "Vol", "Feature": "Fonction", "Gate": "Porte", "Status": "Statut",
 "Above you · every aircraft overhead": "Au-dessus · chaque avion dans le ciel", "Boarding": "Embarquement",
 "Follow any plane on the map": "Suivez n'importe quel avion sur la carte", "On time": "À l'heure",
 "Emergency aircraft in their colours": "Les aéronefs d'urgence à leurs couleurs", "New": "Nouveau",
 "Apple Watch & watch faces": "Apple Watch et cadrans", "Live Activity & widgets": "Activité en direct et widgets",
 "Spotter's Logbook & Sky Bingo": "Carnet d'observation et Bingo du ciel", "Split-flap & Information Board looks": "Styles Palettes et Écran d'information",
 "Follow Me · your flight": "Suivez-moi · votre vol", "The world beneath your wings.": "Le monde sous vos ailes.",
 "Track your flight by GPS, even in airplane mode, and AirReveal names the mountains, cities and coastlines below as you pass them.":
   "Suivez votre vol par GPS, même en mode avion, et AirReveal nomme les montagnes, villes et côtes en dessous à mesure que vous les survolez.",
 "Live": "En direct", "Your position on a full-screen map, with no Wi-Fi needed on board.": "Votre position sur une carte plein écran, sans Wi-Fi à bord.",
 "Plan": "Plan", "Fly the whole route before you go and see what's coming.": "Parcourez tout l'itinéraire avant de partir et voyez ce qui vous attend.",
 "Window View": "Vue hublot", "Hold your phone to the window and landmarks are labelled on the camera picture.": "Tenez votre iPhone contre le hublot et les lieux remarquables s'affichent sur l'image de la caméra.",
 "Best side to sit": "Le meilleur côté", "Left or right, which landmarks you'll see, and whether you'll catch the sunset.": "À gauche ou à droite, les lieux que vous verrez, et si vous aurez le coucher de soleil.",
 "Flight HUD": "HUD de vol", "Altitude, speed and heading over the map, and on the Lock Screen.": "Altitude, vitesse et cap sur la carte et sur l'écran verrouillé.",
 "Journal": "Journal", "Every trip kept, replayed from where you left off.": "Chaque voyage conservé, à reprendre là où vous l'avez laissé.",
 "Window-seat companion": "Le compagnon du hublot", "What am I flying over?": "Qu'est-ce que je survole ?",
 "Every window seat raises the same question. AirReveal answers it at 38,000 feet with only your phone's GPS: download your flight's maps and landmarks before you board, and you're set.":
   "Chaque hublot pose la même question. AirReveal y répond à 38 000 pieds avec le seul GPS de votre iPhone : téléchargez les cartes et lieux de votre vol avant d'embarquer, et c'est prêt.",
 "Works in airplane mode": "Fonctionne en mode avion", "Offline maps": "Cartes hors ligne", "Landmarks named as you pass": "Lieux nommés au passage", "Golden-hour side": "Le côté de l'heure dorée",
 "Follow You · the sky around you": "Je vous suis · le ciel autour de vous", "Who's flying over?": "Qui vole au-dessus ?",
 "Every aircraft around you on a radar and a live map, from free community flight data. Tap one to reveal it.": "Chaque avion autour de vous sur un radar et une carte en direct, grâce à des données de vol communautaires et libres. Touchez-en un pour le découvrir.",
 "Above You Now": "Au-dessus de vous", "The nearest aircraft, how far and which way, with the radar turning to where you face.": "L'avion le plus proche, à quelle distance et dans quelle direction, avec un radar qui s'oriente là où vous regardez.",
 "Day and night maps": "Cartes de jour et de nuit", "Choose the map type; after sunset, Night Lights shows the streets lit below.": "Choisissez le type de carte ; après le coucher du soleil, Lumières nocturnes montre les rues éclairées.",
 "Look up with the camera": "Levez les yeux avec la caméra", "Point at the sky and each plane is marked where it is.": "Pointez le ciel et chaque avion est indiqué là où il se trouve.",
 "Aircraft cards": "Fiches avion", "A photo of that very aircraft, its route, height, speed and type.": "Une photo de cet avion précis, son itinéraire, son altitude, sa vitesse et son type.",
 "Follow it": "Suivez-le", "Keep a plane on the map up to 500 miles away, along the track it really flew.": "Gardez un avion sur la carte jusqu'à 800 km, le long de la trajectoire qu'il a vraiment suivie.",
 "Helicopters too": "Les hélicoptères aussi", "Shown with their own icon, so you know what you're hearing.": "Avec leur propre icône, pour savoir ce que vous entendez.",
 "Blue lights, spotted.": "Gyrophares en vue.",
 "Police, air ambulance, coastguard, firefighting and military aircraft stand out in their own service's colours. Turn on alerts and AirReveal tells you when one comes near, even with the app closed.":
   "Les aéronefs de police, d'ambulance aérienne, de garde-côtes, de lutte contre les incendies et militaires ressortent aux couleurs de leur service. Activez les alertes et AirReveal vous prévient quand l'un d'eux approche, même app fermée.",
 "Air ambulance nearby": "Ambulance aérienne à proximité", "HLE80 (A169), 2 mi NE of you": "HLE80 (A169), à 3 km au NE de vous",
 "Police": "Police", "Black and yellow, as in the UK": "Noir et jaune, comme au Royaume-Uni", "Air ambulance": "Ambulance aérienne", "Yellow and green": "Jaune et vert",
 "Coastguard": "Garde-côtes", "HM Coastguard red and white": "Rouge et blanc des garde-côtes britanniques", "Firefighting": "Lutte contre les incendies", "Yellow and red": "Jaune et rouge",
 "Military": "Militaire", "Olive drab": "Vert olive", "BAW507 · 3 mi E": "BAW507 · 5 km E",
 "Beyond the app": "Au-delà de l'app", "On your wrist, Lock Screen and Home Screen.": "Au poignet, sur l'écran verrouillé et l'écran d'accueil.",
 "A radar you zoom with the Digital Crown, an arrow that points to the plane as you turn, and your flight's progress.": "Un radar que vous zoomez avec la Digital Crown, une flèche qui pointe vers l'avion quand vous tournez, et la progression de votre vol.",
 "Watch faces and Smart Stack": "Cadrans et Pile intelligente", "The nearest aircraft, or the one you follow, right on your watch face.": "L'avion le plus proche, ou celui que vous suivez, sur votre cadran.",
 "Live Activities": "Activités en direct", "The plane you follow on the Lock Screen and in the Dynamic Island: how far, which way, how high.": "L'avion que vous suivez sur l'écran verrouillé et dans la Dynamic Island : à quelle distance, dans quelle direction, à quelle altitude.",
 "Widgets": "Widgets", "Above You on the Home Screen and the Lock Screen, with the radar.": "Au-dessus de vous sur l'écran d'accueil et l'écran verrouillé, avec le radar.",
 "Play along, or don't": "Jouez, ou pas", "Every plane counts.": "Chaque avion compte.",
 "Games for both halves, on your own flights and with the planes above you. Not your thing? Turn them off in Settings and AirReveal is a clean flight tracker.":
   "Des jeux pour les deux côtés, sur vos propres vols et avec les avions au-dessus de vous. Ce n'est pas pour vous ? Désactivez-les dans les Réglages et AirReveal devient un simple suivi de vol.",
 "Spotter's Logbook": "Carnet d'observation", "Every aircraft you reveal, rated common, rare or legendary, with your personal bests.": "Chaque avion que vous découvrez, classé commun, rare ou légendaire, avec vos records personnels.",
 "Bingo and challenges": "Bingo et défis", "Discovery Bingo on your flight, Sky Bingo from home, and three small challenges a day.": "Le Bingo des découvertes en vol, le Bingo du ciel depuis chez vous, et trois petits défis par jour.",
 "Achievements": "Succès", "Stamp your passport, collect landmarks, and spot every emergency service for a badge.": "Tamponnez votre passeport, collectionnez les lieux et repérez chaque service d'urgence pour un badge.",
 "Make it yours": "À votre goût", "Three looks, one app.": "Trois styles, une app.",
 "ABOVE YOU": "AU-DESSUS", "BAW507 12,000 FT": "BAW507 12 000 FT", "3 MI NE · CLOSE": "5 KM NE · PROCHE",
 "Split-Flap": "Palettes", "The flip-letter departure boards: amber on black.": "Les tableaux de départs à palettes : ambre sur noir.",
 "✈ BAW507": "✈ BAW507", "12,000 ft": "12 000 ft", "Distance": "Distance", "3 mi NE": "5 km NE", "Close": "Proche",
 "Information Board": "Écran d'information", "A modern airport screen: white and gold on deep navy.": "Un écran d'aéroport moderne : blanc et or sur bleu marine profond.",
 "BAW507 · A21N": "BAW507 · A21N", "3 mi NE · 12,000 ft": "5 km NE · 12 000 ft",
 "AirReveal Classic": "AirReveal classique", "Cards in your colour theme, in Light or Dark.": "Des cartes à la couleur de votre thème, en clair ou en sombre.",
 "Made for every window seat": "Pour chaque hublot", "Whoever you are, however often you fly.": "Qui que vous soyez, quelle que soit la fréquence de vos vols.",
 "Aviation fans": "Passionnés d'aviation", "Altitude, speed and heading, aircraft types, and a logbook of every plane you spot.": "Altitude, vitesse et cap, types d'avions, et un carnet de chaque avion repéré.",
 "Business travellers": "Voyageurs d'affaires", "A calm map for the same route every week, with something new to notice each time.": "Une carte apaisante pour le même trajet chaque semaine, avec quelque chose de nouveau à remarquer à chaque fois.",
 "Families and holidays": "Familles et vacances", "Which side to sit, what's below, and bingo to keep everyone looking out of the window.": "De quel côté s'asseoir, ce qu'il y a en dessous, et un bingo pour que tout le monde regarde par le hublot.",
 "Curious minds": "Esprits curieux", "Trivia about every landmark and aircraft type, from home or 38,000 feet.": "Des anecdotes sur chaque lieu et chaque type d'avion, depuis chez vous ou à 38 000 pieds.",
 "Take the tour": "La visite", "AirReveal 2.0, screen by screen": "AirReveal 2.0, écran par écran",
 "Questions": "Questions", "Flying over, answered.": "Ce que vous survolez, expliqué.",
 "Final call": "Dernier appel", "Adventure flies with you.": "L'aventure vole avec vous.",
 "AirReveal is on the App Store for iPhone, iPad and Apple Watch. Free to start.": "AirReveal est sur l'App Store pour iPhone, iPad et Apple Watch. Gratuit pour commencer.",
 "User guide": "Guide d'utilisation", "Support": "Assistance", "Privacy": "Confidentialité", "Terms": "Conditions", "Data and credits": "Données et crédits", "Feedback board": "Tableau des idées",
 "© 2026 iSafeNet. Aircraft data from ADSB.lol (ODbL) and plane-alert-db (ODbL). Not an official flight-status or air-traffic service.": "© 2026 iSafeNet. Données avion d'ADSB.lol (ODbL) et de plane-alert-db (ODbL). Ce n'est pas un service officiel de statut des vols ni de contrôle aérien.",
 "Photos on Unsplash: Zac Ong, Kotryna Juskaite, Ben Klewais, Patrick Fore, Nicolas Houdayer.": "Photos sur Unsplash : Zac Ong, Kotryna Juskaite, Ben Klewais, Patrick Fore, Nicolas Houdayer.",
 "Main": "Principal", "AirReveal's home screen: live tracking of your flight and the aircraft above you now": "L'écran d'accueil d'AirReveal : votre vol en direct et les avions au-dessus de vous",
 "What's new in AirReveal 2.0": "Nouveautés d'AirReveal 2.0", "Live flight map": "Carte de vol en direct", "Explore what's below": "Explorez ce qu'il y a en dessous",
 "Above You map around London": "Carte Au-dessus de vous autour de Londres", "Sky camera naming planes overhead": "Caméra du ciel nommant les avions", "Example notification": "Exemple de notification",
 "Following a plane with its recorded track": "Suivi d'un avion avec sa trajectoire enregistrée", "Flight journal": "Journal de vol", "Landmarks to discover": "Lieux à découvrir",
 "Screenshots, scroll sideways": "Captures d'écran, faites défiler sur le côté", "Discover what's above or below you": "Découvrez ce qui est au-dessus ou en dessous de vous", "See where you are": "Voyez où vous êtes",
 "Discover what's below": "Découvrez ce qu'il y a en dessous", "Planes above you": "Les avions au-dessus de vous", "Point at the sky": "Pointez le ciel", "Follow any plane": "Suivez n'importe quel avion",
 "Journal and logbook": "Journal et carnet", "Play as you go": "Jouez en route", "Also in": "Aussi en",
},
"it": {
 "Discover what's above and below.": "Scopri cosa c'è sopra e sotto.", "Discover what's above and below": "Scopri cosa c'è sopra e sotto",
 "Choose your way to fly": "Scegli come volare", "Following a plane": "Seguire un aereo", "Plan freely. Go Pro when you want more.": "Pianifica gratis. Passa a Pro quando vuoi di più.",
 "AirReveal: What Am I Flying Over? Flight Map & Sky Radar": "AirReveal: cosa sto sorvolando? Mappa di volo e radar del cielo",
 "See what you're flying over on your own flight, even in airplane mode, and every plane flying over you on the ground. An offline flight map and live sky radar for iPhone, iPad and Apple Watch.":
   "Guarda cosa sorvoli durante il tuo volo, anche in modalità aereo, e a terra ogni aereo che ti passa sopra. Una mappa di volo offline e un radar del cielo in diretta per iPhone, iPad e Apple Watch.",
 "Below you": "Sotto di te", "Above you": "Sopra di te", "Games": "Giochi", "Pricing": "Prezzi", "FAQ": "FAQ", "Get the app": "Scarica l'app",
 "Flight map & sky radar · iPhone, iPad & Apple Watch": "Mappa di volo e radar del cielo · iPhone, iPad e Apple Watch",
 "Discover what's above or below you.": "Scopri cosa c'è sopra o sotto di te.",
 "From your window seat, AirReveal names the mountains, cities and coastlines below, even in airplane mode. On the ground, it shows every plane flying over you, where it's going, and the police and air ambulance helicopters in their own colours.":
   "Dal finestrino, AirReveal dà un nome a montagne, città e coste sotto di te, anche in modalità aereo. A terra mostra ogni aereo che ti sorvola, dove va, e gli elicotteri della polizia e delle eliambulanze nei loro colori.",
 "Download on the": "Scarica su", "Free to start · 2.0 is here": "Gratis per iniziare · La 2.0 è qui",
 "Departures": "Partenze", "New in 2.0": "Novità della 2.0", "Flight": "Volo", "Feature": "Funzione", "Gate": "Gate", "Status": "Stato",
 "Above you · every aircraft overhead": "Sopra di te · ogni aereo in cielo", "Boarding": "Imbarco",
 "Follow any plane on the map": "Segui qualsiasi aereo sulla mappa", "On time": "In orario",
 "Emergency aircraft in their colours": "Aerei di emergenza nei loro colori", "New": "Nuovo",
 "Apple Watch & watch faces": "Apple Watch e quadranti", "Live Activity & widgets": "Attività in tempo reale e widget",
 "Spotter's Logbook & Sky Bingo": "Diario di avvistamenti e Bingo del cielo", "Split-flap & Information Board looks": "Stili Palette e Tabellone informativo",
 "Follow Me · your flight": "Seguimi · il tuo volo", "The world beneath your wings.": "Il mondo sotto le tue ali.",
 "Track your flight by GPS, even in airplane mode, and AirReveal names the mountains, cities and coastlines below as you pass them.":
   "Segui il tuo volo via GPS, anche in modalità aereo, e AirReveal dà un nome a montagne, città e coste sotto di te mentre le sorvoli.",
 "Live": "Live", "Your position on a full-screen map, with no Wi-Fi needed on board.": "La tua posizione su una mappa a tutto schermo, senza Wi-Fi a bordo.",
 "Plan": "Piano", "Fly the whole route before you go and see what's coming.": "Percorri tutta la rotta prima di partire e scopri cosa ti aspetta.",
 "Window View": "Vista dal finestrino", "Hold your phone to the window and landmarks are labelled on the camera picture.": "Avvicina l'iPhone al finestrino e i luoghi d'interesse compaiono sull'immagine della fotocamera.",
 "Best side to sit": "Il lato migliore", "Left or right, which landmarks you'll see, and whether you'll catch the sunset.": "Sinistra o destra, quali luoghi vedrai e se ti godrai il tramonto.",
 "Flight HUD": "HUD di volo", "Altitude, speed and heading over the map, and on the Lock Screen.": "Altitudine, velocità e rotta sulla mappa e sulla schermata di blocco.",
 "Journal": "Diario", "Every trip kept, replayed from where you left off.": "Ogni viaggio salvato, da rivivere da dove l'avevi lasciato.",
 "Window-seat companion": "Il compagno del finestrino", "What am I flying over?": "Cosa sto sorvolando?",
 "Every window seat raises the same question. AirReveal answers it at 38,000 feet with only your phone's GPS: download your flight's maps and landmarks before you board, and you're set.":
   "Ogni finestrino fa nascere la stessa domanda. AirReveal risponde a 38.000 piedi con il solo GPS del tuo iPhone: scarica mappe e luoghi del volo prima dell'imbarco ed è fatta.",
 "Works in airplane mode": "Funziona in modalità aereo", "Offline maps": "Mappe offline", "Landmarks named as you pass": "Luoghi nominati al passaggio", "Golden-hour side": "Il lato dell'ora d'oro",
 "Follow You · the sky around you": "Ti seguo · il cielo intorno a te", "Who's flying over?": "Chi sta volando sopra?",
 "Every aircraft around you on a radar and a live map, from free community flight data. Tap one to reveal it.": "Ogni aereo intorno a te su un radar e una mappa in diretta, con dati di volo liberi della community. Toccane uno per scoprirlo.",
 "Above You Now": "Sopra di te ora", "The nearest aircraft, how far and which way, with the radar turning to where you face.": "L'aereo più vicino, quanto è lontano e in che direzione, con il radar che ruota dove guardi.",
 "Day and night maps": "Mappe di giorno e di notte", "Choose the map type; after sunset, Night Lights shows the streets lit below.": "Scegli il tipo di mappa; dopo il tramonto, Luci notturne mostra le strade illuminate.",
 "Look up with the camera": "Guarda in alto con la fotocamera", "Point at the sky and each plane is marked where it is.": "Inquadra il cielo e ogni aereo viene segnato dov'è.",
 "Aircraft cards": "Schede degli aerei", "A photo of that very aircraft, its route, height, speed and type.": "Una foto proprio di quell'aereo, la rotta, la quota, la velocità e il tipo.",
 "Follow it": "Seguilo", "Keep a plane on the map up to 500 miles away, along the track it really flew.": "Tieni un aereo sulla mappa fino a 800 km di distanza, lungo la traccia che ha davvero percorso.",
 "Helicopters too": "Anche elicotteri", "Shown with their own icon, so you know what you're hearing.": "Con la loro icona, così sai cosa stai sentendo.",
 "Blue lights, spotted.": "Lampeggianti avvistati.",
 "Police, air ambulance, coastguard, firefighting and military aircraft stand out in their own service's colours. Turn on alerts and AirReveal tells you when one comes near, even with the app closed.":
   "Gli aerei di polizia, eliambulanza, guardia costiera, antincendio e militari risaltano nei colori del loro servizio. Attiva gli avvisi e AirReveal ti dice quando uno si avvicina, anche con l'app chiusa.",
 "Air ambulance nearby": "Eliambulanza nelle vicinanze", "HLE80 (A169), 2 mi NE of you": "HLE80 (A169), a 3 km a NE da te",
 "Police": "Polizia", "Black and yellow, as in the UK": "Nero e giallo, come nel Regno Unito", "Air ambulance": "Eliambulanza", "Yellow and green": "Giallo e verde",
 "Coastguard": "Guardia costiera", "HM Coastguard red and white": "Rosso e bianco della guardia costiera britannica", "Firefighting": "Antincendio", "Yellow and red": "Giallo e rosso",
 "Military": "Militare", "Olive drab": "Verde oliva", "BAW507 · 3 mi E": "BAW507 · 5 km E",
 "Beyond the app": "Oltre l'app", "On your wrist, Lock Screen and Home Screen.": "Al polso, sulla schermata di blocco e su quella Home.",
 "A radar you zoom with the Digital Crown, an arrow that points to the plane as you turn, and your flight's progress.": "Un radar da zoomare con la Digital Crown, una freccia che punta all'aereo mentre ti giri e l'avanzamento del tuo volo.",
 "Watch faces and Smart Stack": "Quadranti e Pila smart", "The nearest aircraft, or the one you follow, right on your watch face.": "L'aereo più vicino, o quello che segui, direttamente sul quadrante.",
 "Live Activities": "Attività in tempo reale", "The plane you follow on the Lock Screen and in the Dynamic Island: how far, which way, how high.": "L'aereo che segui sulla schermata di blocco e nella Dynamic Island: quanto è lontano, in che direzione, a che quota.",
 "Widgets": "Widget", "Above You on the Home Screen and the Lock Screen, with the radar.": "Sopra di te sulla schermata Home e su quella di blocco, con il radar.",
 "Play along, or don't": "Gioca, o no", "Every plane counts.": "Ogni aereo conta.",
 "Games for both halves, on your own flights and with the planes above you. Not your thing? Turn them off in Settings and AirReveal is a clean flight tracker.":
   "Giochi per entrambe le metà, sui tuoi voli e con gli aerei sopra di te. Non fanno per te? Disattivali nelle Impostazioni e AirReveal diventa un semplice tracker di voli.",
 "Spotter's Logbook": "Diario di avvistamenti", "Every aircraft you reveal, rated common, rare or legendary, with your personal bests.": "Ogni aereo che scopri, classificato comune, raro o leggendario, con i tuoi record personali.",
 "Bingo and challenges": "Bingo e sfide", "Discovery Bingo on your flight, Sky Bingo from home, and three small challenges a day.": "Il Bingo delle scoperte in volo, il Bingo del cielo da casa e tre piccole sfide al giorno.",
 "Achievements": "Traguardi", "Stamp your passport, collect landmarks, and spot every emergency service for a badge.": "Timbra il passaporto, colleziona luoghi e avvista ogni servizio di emergenza per un badge.",
 "Make it yours": "A modo tuo", "Three looks, one app.": "Tre stili, un'app.",
 "ABOVE YOU": "SOPRA DI TE", "BAW507 12,000 FT": "BAW507 12.000 FT", "3 MI NE · CLOSE": "5 KM NE · VICINO",
 "Split-Flap": "Palette", "The flip-letter departure boards: amber on black.": "I tabelloni delle partenze a palette: ambra su nero.",
 "✈ BAW507": "✈ BAW507", "12,000 ft": "12.000 ft", "Distance": "Distanza", "3 mi NE": "5 km NE", "Close": "Vicino",
 "Information Board": "Tabellone informativo", "A modern airport screen: white and gold on deep navy.": "Uno schermo da aeroporto moderno: bianco e oro su blu notte.",
 "BAW507 · A21N": "BAW507 · A21N", "3 mi NE · 12,000 ft": "5 km NE · 12.000 ft",
 "AirReveal Classic": "AirReveal classico", "Cards in your colour theme, in Light or Dark.": "Schede nel colore del tuo tema, chiaro o scuro.",
 "Made for every window seat": "Per ogni finestrino", "Whoever you are, however often you fly.": "Chiunque tu sia, quanto spesso tu voli.",
 "Aviation fans": "Appassionati di aviazione", "Altitude, speed and heading, aircraft types, and a logbook of every plane you spot.": "Quota, velocità e rotta, tipi di aereo e un diario di ogni aereo avvistato.",
 "Business travellers": "Viaggiatori d'affari", "A calm map for the same route every week, with something new to notice each time.": "Una mappa tranquilla per la stessa rotta ogni settimana, con qualcosa di nuovo da notare ogni volta.",
 "Families and holidays": "Famiglie e vacanze", "Which side to sit, what's below, and bingo to keep everyone looking out of the window.": "Da che lato sedersi, cosa c'è sotto e un bingo per far guardare tutti fuori dal finestrino.",
 "Curious minds": "Menti curiose", "Trivia about every landmark and aircraft type, from home or 38,000 feet.": "Curiosità su ogni luogo e tipo di aereo, da casa o a 38.000 piedi.",
 "Take the tour": "Fai il giro", "AirReveal 2.0, screen by screen": "AirReveal 2.0, schermata per schermata",
 "Questions": "Domande", "Flying over, answered.": "Cosa sorvoli, spiegato.",
 "Final call": "Ultima chiamata", "Adventure flies with you.": "L'avventura vola con te.",
 "AirReveal is on the App Store for iPhone, iPad and Apple Watch. Free to start.": "AirReveal è sull'App Store per iPhone, iPad e Apple Watch. Gratis per iniziare.",
 "User guide": "Guida all'uso", "Support": "Assistenza", "Privacy": "Privacy", "Terms": "Termini", "Data and credits": "Dati e crediti", "Feedback board": "Bacheca dei suggerimenti",
 "© 2026 iSafeNet. Aircraft data from ADSB.lol (ODbL) and plane-alert-db (ODbL). Not an official flight-status or air-traffic service.": "© 2026 iSafeNet. Dati sugli aerei da ADSB.lol (ODbL) e plane-alert-db (ODbL). Non è un servizio ufficiale di stato dei voli o di traffico aereo.",
 "Photos on Unsplash: Zac Ong, Kotryna Juskaite, Ben Klewais, Patrick Fore, Nicolas Houdayer.": "Foto su Unsplash: Zac Ong, Kotryna Juskaite, Ben Klewais, Patrick Fore, Nicolas Houdayer.",
 "Main": "Principale", "AirReveal's home screen: live tracking of your flight and the aircraft above you now": "La schermata iniziale di AirReveal: il tuo volo in diretta e gli aerei sopra di te ora",
 "What's new in AirReveal 2.0": "Novità di AirReveal 2.0", "Live flight map": "Mappa di volo in diretta", "Explore what's below": "Esplora cosa c'è sotto",
 "Above You map around London": "Mappa Sopra di te intorno a Londra", "Sky camera naming planes overhead": "Fotocamera del cielo che nomina gli aerei", "Example notification": "Notifica di esempio",
 "Following a plane with its recorded track": "Seguire un aereo con la sua traccia registrata", "Flight journal": "Diario di volo", "Landmarks to discover": "Luoghi da scoprire",
 "Screenshots, scroll sideways": "Schermate, scorri di lato", "Discover what's above or below you": "Scopri cosa c'è sopra o sotto di te", "See where you are": "Guarda dove sei",
 "Discover what's below": "Scopri cosa c'è sotto", "Planes above you": "Gli aerei sopra di te", "Point at the sky": "Inquadra il cielo", "Follow any plane": "Segui qualsiasi aereo",
 "Journal and logbook": "Diario e registro", "Play as you go": "Gioca mentre viaggi", "Also in": "Anche in",
},
"pt-br": {
 "Discover what's above and below.": "Descubra o que há acima e abaixo.", "Discover what's above and below": "Descubra o que há acima e abaixo",
 "Choose your way to fly": "Escolha como voar", "Following a plane": "Seguindo um avião", "Plan freely. Go Pro when you want more.": "Planeje grátis. Assine o Pro quando quiser mais.",
 "AirReveal: What Am I Flying Over? Flight Map & Sky Radar": "AirReveal: o que estou sobrevoando? Mapa de voo e radar do céu",
 "See what you're flying over on your own flight, even in airplane mode, and every plane flying over you on the ground. An offline flight map and live sky radar for iPhone, iPad and Apple Watch.":
   "Veja o que você está sobrevoando no seu voo, mesmo no modo avião, e em terra cada avião que passa acima de você. Um mapa de voo offline e um radar do céu ao vivo para iPhone, iPad e Apple Watch.",
 "Below you": "Abaixo de você", "Above you": "Acima de você", "Games": "Jogos", "Pricing": "Preços", "FAQ": "Perguntas", "Get the app": "Baixar o app",
 "Flight map & sky radar · iPhone, iPad & Apple Watch": "Mapa de voo e radar do céu · iPhone, iPad e Apple Watch",
 "Discover what's above or below you.": "Descubra o que está acima ou abaixo de você.",
 "From your window seat, AirReveal names the mountains, cities and coastlines below, even in airplane mode. On the ground, it shows every plane flying over you, where it's going, and the police and air ambulance helicopters in their own colours.":
   "Da janela, o AirReveal dá nome às montanhas, cidades e litorais lá embaixo, mesmo no modo avião. Em terra, mostra cada avião que passa acima de você, para onde vai, e os helicópteros da polícia e de ambulância aérea com suas próprias cores.",
 "Download on the": "Baixar na", "Free to start · 2.0 is here": "Grátis para começar · A 2.0 chegou",
 "Departures": "Partidas", "New in 2.0": "Novidades da 2.0", "Flight": "Voo", "Feature": "Recurso", "Gate": "Portão", "Status": "Situação",
 "Above you · every aircraft overhead": "Acima de você · cada avião no céu", "Boarding": "Embarque",
 "Follow any plane on the map": "Siga qualquer avião no mapa", "On time": "No horário",
 "Emergency aircraft in their colours": "Aeronaves de emergência com suas cores", "New": "Novo",
 "Apple Watch & watch faces": "Apple Watch e mostradores", "Live Activity & widgets": "Atividade ao Vivo e widgets",
 "Spotter's Logbook & Sky Bingo": "Diário de avistamentos e Bingo do céu", "Split-flap & Information Board looks": "Estilos Painel de palhetas e Painel informativo",
 "Follow Me · your flight": "Me siga · seu voo", "The world beneath your wings.": "O mundo sob suas asas.",
 "Track your flight by GPS, even in airplane mode, and AirReveal names the mountains, cities and coastlines below as you pass them.":
   "Acompanhe seu voo por GPS, mesmo no modo avião, e o AirReveal dá nome às montanhas, cidades e litorais lá embaixo conforme você passa.",
 "Live": "Ao vivo", "Your position on a full-screen map, with no Wi-Fi needed on board.": "Sua posição num mapa em tela cheia, sem precisar de Wi-Fi a bordo.",
 "Plan": "Plano", "Fly the whole route before you go and see what's coming.": "Percorra a rota inteira antes de ir e veja o que vem pela frente.",
 "Window View": "Vista da janela", "Hold your phone to the window and landmarks are labelled on the camera picture.": "Encoste o iPhone na janela e os pontos de interesse aparecem marcados na imagem da câmera.",
 "Best side to sit": "O melhor lado", "Left or right, which landmarks you'll see, and whether you'll catch the sunset.": "Esquerda ou direita, quais lugares você vai ver e se vai pegar o pôr do sol.",
 "Flight HUD": "HUD de voo", "Altitude, speed and heading over the map, and on the Lock Screen.": "Altitude, velocidade e rumo sobre o mapa e na Tela Bloqueada.",
 "Journal": "Diário", "Every trip kept, replayed from where you left off.": "Cada viagem guardada, para rever de onde você parou.",
 "Window-seat companion": "O companheiro da janela", "What am I flying over?": "O que estou sobrevoando?",
 "Every window seat raises the same question. AirReveal answers it at 38,000 feet with only your phone's GPS: download your flight's maps and landmarks before you board, and you're set.":
   "Toda janela faz a mesma pergunta. O AirReveal responde a 38.000 pés só com o GPS do seu iPhone: baixe os mapas e lugares do seu voo antes de embarcar e pronto.",
 "Works in airplane mode": "Funciona no modo avião", "Offline maps": "Mapas offline", "Landmarks named as you pass": "Lugares nomeados ao passar", "Golden-hour side": "O lado da hora dourada",
 "Follow You · the sky around you": "Te sigo · o céu ao seu redor", "Who's flying over?": "Quem está voando por cima?",
 "Every aircraft around you on a radar and a live map, from free community flight data. Tap one to reveal it.": "Cada avião ao seu redor num radar e num mapa ao vivo, com dados de voo livres da comunidade. Toque em um para revelá-lo.",
 "Above You Now": "Acima de você agora", "The nearest aircraft, how far and which way, with the radar turning to where you face.": "O avião mais próximo, a que distância e em que direção, com o radar girando para onde você olha.",
 "Day and night maps": "Mapas de dia e de noite", "Choose the map type; after sunset, Night Lights shows the streets lit below.": "Escolha o tipo de mapa; depois do pôr do sol, Luzes noturnas mostra as ruas iluminadas.",
 "Look up with the camera": "Olhe para cima com a câmera", "Point at the sky and each plane is marked where it is.": "Aponte para o céu e cada avião aparece marcado onde está.",
 "Aircraft cards": "Fichas dos aviões", "A photo of that very aircraft, its route, height, speed and type.": "Uma foto daquele mesmo avião, sua rota, altitude, velocidade e tipo.",
 "Follow it": "Siga-o", "Keep a plane on the map up to 500 miles away, along the track it really flew.": "Mantenha um avião no mapa a até 800 km, pela rota que ele realmente voou.",
 "Helicopters too": "Helicópteros também", "Shown with their own icon, so you know what you're hearing.": "Com um ícone próprio, para você saber o que está ouvindo.",
 "Blue lights, spotted.": "Giroflex à vista.",
 "Police, air ambulance, coastguard, firefighting and military aircraft stand out in their own service's colours. Turn on alerts and AirReveal tells you when one comes near, even with the app closed.":
   "Aeronaves de polícia, ambulância aérea, guarda costeira, combate a incêndios e militares se destacam nas cores do seu serviço. Ative os alertas e o AirReveal avisa quando uma se aproxima, mesmo com o app fechado.",
 "Air ambulance nearby": "Ambulância aérea por perto", "HLE80 (A169), 2 mi NE of you": "HLE80 (A169), a 3 km a NE de você",
 "Police": "Polícia", "Black and yellow, as in the UK": "Preto e amarelo, como no Reino Unido", "Air ambulance": "Ambulância aérea", "Yellow and green": "Amarelo e verde",
 "Coastguard": "Guarda costeira", "HM Coastguard red and white": "Vermelho e branco da Guarda Costeira britânica", "Firefighting": "Combate a incêndios", "Yellow and red": "Amarelo e vermelho",
 "Military": "Militar", "Olive drab": "Verde-oliva", "BAW507 · 3 mi E": "BAW507 · 5 km L",
 "Beyond the app": "Além do app", "On your wrist, Lock Screen and Home Screen.": "No pulso, na Tela Bloqueada e na Tela de Início.",
 "A radar you zoom with the Digital Crown, an arrow that points to the plane as you turn, and your flight's progress.": "Um radar que você amplia com a Digital Crown, uma seta que aponta para o avião enquanto você gira e o progresso do seu voo.",
 "Watch faces and Smart Stack": "Mostradores e Pilha Inteligente", "The nearest aircraft, or the one you follow, right on your watch face.": "O avião mais próximo, ou o que você segue, direto no seu mostrador.",
 "Live Activities": "Atividades ao Vivo", "The plane you follow on the Lock Screen and in the Dynamic Island: how far, which way, how high.": "O avião que você segue na Tela Bloqueada e na Dynamic Island: a que distância, em que direção, a que altitude.",
 "Widgets": "Widgets", "Above You on the Home Screen and the Lock Screen, with the radar.": "Acima de você na Tela de Início e na Tela Bloqueada, com o radar.",
 "Play along, or don't": "Jogue, ou não", "Every plane counts.": "Cada avião conta.",
 "Games for both halves, on your own flights and with the planes above you. Not your thing? Turn them off in Settings and AirReveal is a clean flight tracker.":
   "Jogos para os dois lados, nos seus voos e com os aviões acima de você. Não é a sua? Desligue nos Ajustes e o AirReveal vira um rastreador de voos simples.",
 "Spotter's Logbook": "Diário de avistamentos", "Every aircraft you reveal, rated common, rare or legendary, with your personal bests.": "Cada avião que você revela, classificado como comum, raro ou lendário, com seus recordes pessoais.",
 "Bingo and challenges": "Bingo e desafios", "Discovery Bingo on your flight, Sky Bingo from home, and three small challenges a day.": "Bingo de Descobertas no voo, Bingo do céu em casa e três pequenos desafios por dia.",
 "Achievements": "Conquistas", "Stamp your passport, collect landmarks, and spot every emergency service for a badge.": "Carimbe seu passaporte, colecione lugares e aviste cada serviço de emergência para ganhar um selo.",
 "Make it yours": "Do seu jeito", "Three looks, one app.": "Três estilos, um app.",
 "ABOVE YOU": "ACIMA DE VOCÊ", "BAW507 12,000 FT": "BAW507 12.000 FT", "3 MI NE · CLOSE": "5 KM NE · PERTO",
 "Split-Flap": "Painel de palhetas", "The flip-letter departure boards: amber on black.": "Os painéis de partidas de palhetas: âmbar sobre preto.",
 "✈ BAW507": "✈ BAW507", "12,000 ft": "12.000 ft", "Distance": "Distância", "3 mi NE": "5 km NE", "Close": "Perto",
 "Information Board": "Painel informativo", "A modern airport screen: white and gold on deep navy.": "Uma tela de aeroporto moderna: branco e dourado sobre azul-marinho.",
 "BAW507 · A21N": "BAW507 · A21N", "3 mi NE · 12,000 ft": "5 km NE · 12.000 ft",
 "AirReveal Classic": "AirReveal clássico", "Cards in your colour theme, in Light or Dark.": "Cartões na cor do seu tema, claro ou escuro.",
 "Made for every window seat": "Para cada janela", "Whoever you are, however often you fly.": "Seja quem for, voe quanto voar.",
 "Aviation fans": "Fãs de aviação", "Altitude, speed and heading, aircraft types, and a logbook of every plane you spot.": "Altitude, velocidade e rumo, tipos de avião e um diário de cada avião avistado.",
 "Business travellers": "Viajantes a negócios", "A calm map for the same route every week, with something new to notice each time.": "Um mapa tranquilo para a mesma rota toda semana, com algo novo para notar a cada vez.",
 "Families and holidays": "Famílias e férias", "Which side to sit, what's below, and bingo to keep everyone looking out of the window.": "De que lado sentar, o que tem lá embaixo e um bingo para todo mundo olhar pela janela.",
 "Curious minds": "Mentes curiosas", "Trivia about every landmark and aircraft type, from home or 38,000 feet.": "Curiosidades sobre cada lugar e tipo de avião, de casa ou a 38.000 pés.",
 "Take the tour": "Faça o tour", "AirReveal 2.0, screen by screen": "AirReveal 2.0, tela por tela",
 "Questions": "Perguntas", "Flying over, answered.": "O que você sobrevoa, respondido.",
 "Final call": "Última chamada", "Adventure flies with you.": "A aventura voa com você.",
 "AirReveal is on the App Store for iPhone, iPad and Apple Watch. Free to start.": "O AirReveal está na App Store para iPhone, iPad e Apple Watch. Grátis para começar.",
 "User guide": "Guia de uso", "Support": "Suporte", "Privacy": "Privacidade", "Terms": "Termos", "Data and credits": "Dados e créditos", "Feedback board": "Mural de sugestões",
 "© 2026 iSafeNet. Aircraft data from ADSB.lol (ODbL) and plane-alert-db (ODbL). Not an official flight-status or air-traffic service.": "© 2026 iSafeNet. Dados de aviões do ADSB.lol (ODbL) e do plane-alert-db (ODbL). Não é um serviço oficial de status de voos nem de tráfego aéreo.",
 "Photos on Unsplash: Zac Ong, Kotryna Juskaite, Ben Klewais, Patrick Fore, Nicolas Houdayer.": "Fotos no Unsplash: Zac Ong, Kotryna Juskaite, Ben Klewais, Patrick Fore, Nicolas Houdayer.",
 "Main": "Principal", "AirReveal's home screen: live tracking of your flight and the aircraft above you now": "A tela inicial do AirReveal: seu voo ao vivo e os aviões acima de você agora",
 "What's new in AirReveal 2.0": "Novidades do AirReveal 2.0", "Live flight map": "Mapa de voo ao vivo", "Explore what's below": "Explore o que há lá embaixo",
 "Above You map around London": "Mapa Acima de você em Londres", "Sky camera naming planes overhead": "Câmera do céu nomeando os aviões", "Example notification": "Notificação de exemplo",
 "Following a plane with its recorded track": "Seguindo um avião com a rota registrada", "Flight journal": "Diário de voo", "Landmarks to discover": "Lugares para descobrir",
 "Screenshots, scroll sideways": "Capturas de tela, role para o lado", "Discover what's above or below you": "Descubra o que está acima ou abaixo de você", "See where you are": "Veja onde você está",
 "Discover what's below": "Descubra o que há lá embaixo", "Planes above you": "Aviões acima de você", "Point at the sky": "Aponte para o céu", "Follow any plane": "Siga qualquer avião",
 "Journal and logbook": "Diário e registro", "Play as you go": "Jogue durante a viagem", "Also in": "Também em",
},
}

# The two questions new in 2.0; the rest of the home page's questions come from site_i18n's translations.
NEW_FAQ = {
 "de": [("Welche Flugzeuge fliegen über mein Haus?", "„Gerade über dir“ zeigt jedes Flugzeug um dich herum auf einem Radar und einer Live-Karte, aus freien Community-Flugdaten. Tippe eines an, um seine Route, seinen Typ, seine Höhe und ein Foto genau dieses Flugzeugs zu sehen."),
        ("Kann AirReveal mir sagen, wenn ein Polizei- oder Rettungshubschrauber in der Nähe ist?", "Ja. Polizei, Luftrettung, Küstenwache, Brandbekämpfung und Militär werden in ihren eigenen Farben gezeigt, und du kannst Hinweise für die Dienste einschalten, die du auswählst, innerhalb einer Entfernung, die du festlegst. Hinweise sind aus, bis du sie einschaltest.")],
 "es": [("¿Qué aviones están volando sobre mi casa?", "Encima de ti ahora muestra cada avión a tu alrededor en un radar y un mapa en directo, con datos de vuelo libres de la comunidad. Toca uno para ver su ruta, su tipo, su altura y una foto de ese mismo avión."),
        ("¿Puede AirReveal avisarme cuando hay un helicóptero de policía o de ambulancia aérea cerca?", "Sí. Las aeronaves de policía, ambulancia aérea, guardacostas, extinción de incendios y militares se muestran con sus propios colores, y puedes activar avisos para las que elijas, dentro de la distancia que fijes. Los avisos están desactivados hasta que los actives.")],
 "fr": [("Quels avions survolent ma maison ?", "Au-dessus de vous affiche chaque avion autour de vous sur un radar et une carte en direct, grâce à des données de vol communautaires et libres. Touchez-en un pour voir son itinéraire, son type, son altitude et une photo de cet avion précis."),
        ("AirReveal peut-il me prévenir quand un hélicoptère de police ou d'ambulance aérienne est proche ?", "Oui. Les aéronefs de police, d'ambulance aérienne, de garde-côtes, de lutte contre les incendies et militaires s'affichent à leurs propres couleurs, et vous pouvez activer des alertes pour ceux que vous choisissez, dans un rayon que vous fixez. Les alertes restent désactivées tant que vous ne les activez pas.")],
 "it": [("Quali aerei stanno sorvolando casa mia?", "Sopra di te ora mostra ogni aereo intorno a te su un radar e una mappa in diretta, con dati di volo liberi della community. Toccane uno per vederne la rotta, il tipo, la quota e una foto proprio di quell'aereo."),
        ("AirReveal può avvisarmi quando c'è vicino un elicottero della polizia o un'eliambulanza?", "Sì. Gli aerei di polizia, eliambulanza, guardia costiera, antincendio e militari vengono mostrati nei loro colori, e puoi attivare gli avvisi per quelli che scegli, entro la distanza che imposti. Gli avvisi restano spenti finché non li attivi.")],
 "pt-br": [("Quais aviões estão voando sobre a minha casa?", "Acima de você agora mostra cada avião ao seu redor num radar e num mapa ao vivo, com dados de voo livres da comunidade. Toque em um para ver a rota, o tipo, a altitude e uma foto daquele mesmo avião."),
        ("O AirReveal pode me avisar quando um helicóptero da polícia ou de ambulância aérea estiver por perto?", "Sim. Aeronaves de polícia, ambulância aérea, guarda costeira, combate a incêndios e militares aparecem com suas próprias cores, e você pode ativar alertas para as que escolher, dentro da distância que definir. Os alertas ficam desligados até você ativá-los.")],
}
